SRCDIR		= ./src
VPATH		= $(SRCDIR)
SRC_C		= src/font_drawing.c src/pcfx.c src/common.c src/main.c
SRC_S		= src/font.s src/fastking.s
OBJ_C		= $(notdir $(patsubst %.c, %.o, $(SRC_C)))
OBJ_S		= $(notdir $(patsubst %.s, %.o, $(SRC_S)))
CD_OBJECTS	   = 
OBJECTS        = $(OBJ_C) $(OBJ_S)
ELF_TARGET     = mytest.elf
BIN_TARGET     = mytest.bin
ADD_FILES      = 
CD_FILES	   = 
CDOUT          = mytest_cd

include example.mk
